config/routes.rb
Rails.application.routes.draw do

  root to: 'leagues#index'

  resources :leagues do
    resources :teams do
      resources :players do
        post 'draft'
      end
    end
    resources :plays_on
    member do
      get 'draft'
    end
  end

  resources :players 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams, :dependent => :destroy


  def add_teams
    team_names = names.shuffle
    12.times do |i|
      self.teams.create!(name: "#{team_names[i]}")
    end
  end

  def names
    ['13 Reasons Ajayi',
      '99 Problems But a Fitz Ain’t One',
      'A Gronking in December',
      'Abdullah Oblongata',
      'Ain’t No Such Thing as Halfway Cooks',
      'Ajayi Another Day',
      'Al Hurns and Gurley',
      'All About the Benjamins',
      'All I Do is Winston',
      'All That I Snead',
      'All You Snead is Love',
      'Alshon of the Dead',
      'Amari 2600',
      'Amari Teenage Riot',
      'Baby Got Dak',
      'Bad and BouBrees',
      'Bilal Weve Got',
      'Blount Force Trauma',
      'Blountsprout and Ivorysaur',
      'Boldin the Beautiful',
      'Boom Boom Powell',
      'Born to Maclin',
      'Bortles Service',
      'Brees the Sheriff',
      'Bringin’ the Woodhead',
      'Can You Diggs It?',
      'Cant Stop the Thielen',
      'Christian Missionaries',
      'Chronicles of Riddick',
      'Clam Crowder',
      'Cobb Deep',
      'Crowella du Ville',
      'Czar of the Martellustrator',
      'Dak and Yellow',
      'Dakstreets Back',
      'Daltons Abbey',
      'Dandy Merediths',
      'Death Ertz-tificate',
      'Demaryius Had A Little Lamb',
      'Deshaun of the Dead',
      'DeVante’s Inferno',
      'Dez Dispensers',
      'Diggs in a Blanket',
      'Dirty Landry',
      'Dont Eli To My Face',
      'Dude Wheres My Carr?',
      'Dude Youre Getting O-Dell!',
      'Eastbound and Brown',
      'El Gordo Y La Flacco',
      'Ezekiel 25:17',
      'Fanatical Christians',
      'FartSmellus Buttnutt',
      'Fleener Than a Junkyard Dog',
      'Floyd Rage',
      'For the Winston',
      'Fournettecation',
      'Frankly Ameer I Dont Give a Damn',
      'Games of Jones',
      'Get Your Tyreek On',
      'Giovani Vidi Vici',
      'Golden Grahams',
      'Golden McCaffrey',
      'Gone Gurley',
      'Gore Values',
      'Gould Members',
      'Green Eggs and Beckham',
      'Green Initiative',
      'Gym, Tannehill, Landry',
      'Here’s My Number, So Call Me Brady',
      'Highway to Bell',
      'Honeybaked Beckham',
      'Hooked on a Thielen',
      'Hot Lockett',
      'Hurns Notice',
      'Hyde and Go Luck Yourself',
      'Hyde and Tyreek',
      'I Gotta Thielen',
      'Ill Make You Jameis',
      'Ingram Toenails',
      'InstaGraham',
      'It’s Von Like Donkey Kong',
      'Jamaal About That Bass',
      'Johnson and More Johnson',
      'Just Say Wentz',
      'Keenan-Ivory-Dwaynes',
      'Keep Choppin’ Woodhead',
      'Kelce Lately',
      'Kissing Cousins Good-bye',
      'Kizer Wide Shut',
      'Lacy Underalls',
      'Ladies and Edelman',
      'Lamar the Merrier!',
      'Lamar You Serious?',
      'Land of the Freeman',
      'Landry Service',
      'LeVeon a Prayer',
      'Let Sleeping Dogs Eli',
      'Lets Get Riddickulous!',
      'Make Demaryica Great Again!',
      'Mariota Had a Little Lamb',
      'Mariota Kart',
      'Marshawn of the Dead',
      'Martellus All About It',
      'MegaErtz',
      'Mercedes Wentz',
      'Miller’s Bossin’',
      'More than a Thielen',
      'Mr. Rodgers Neighborhood',
      'O-Dell No',
      'Palmer? I Hardly Know Her!',
      'Peachy Keenan',
      'Pimpin Aint Breesy',
      'Pocket Lockett',
      'Pop-Lockett-Drop It',
      'Poppin Bortles',
      'Praise the Jord-y',
      'Rage Against the Vereen',
      'Rawls Royces',
      'Rebel Yeldons',
      'Reeding Rainbow',
      'Roethlisberger Helper',
      'Rudolph the Red-Zone Reindeer',
      'Sanu Jack City',
      'Saving Matt Ryan',
      'Scobee Snacks',
      'Serial Miller',
      'Shadys Gurley Party',
      'Sims City',
      'Song of Matty Ice and Fire',
      'Special Zay',
      'Stacked Deckers',
      'Staff Infection',
      'Stairway to Evans',
      'Steady Cams',
      'Steady Cobbin’',
      'Sterling SilverWare',
      'Suh-and-a-Half Men',
      'Suh-Tang Clan (Aint Nuthing Ta F Wit)',
      'T.Y. Dolla $ign',
      'T.Y. Very Much',
      'Take em to the Woodhead',
      'Tate is Enough',
      'Tate Misbehavin',
      'Thats Bilal Folks!',
      'The Backfields & McCoys',
      'The Big Gronkowski',
      'The Black Crowells',
      'The Counting Crowells',
      'The Gurley Gates',
      'The Hauschka Always Wins',
      'The Jeremy Hills Have Eyes',
      'The Mixon Administration',
      'The Tannehills Have Eyes',
      'Thielen Like Makin Love',
      'To Be Prosise',
      'Touchdown Breesus',
      'Turn Down for Watkins',
      'Turn Down for Watt',
      'Turn Goff the Lights',
      'Upper Deckers',
      'View From Lamar',
      'Ware Bears',
      'We’re Allen this Together',
      'Wings of a Davante',
      'Winning is My Forte',
      'Yippee Ki Yay Justin Tucker',
      'You Know You Gano Lose',
      'Your Brate Is Sealed',
      'Zeke Squad']
    end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @league = League.find(params[:id])
  end

  # GET /leagues/new
  def new
    league_name = (1 + rand(10000))
    @league = League.new(name: "League #{league_name}")
    @players = Player.all
  end

  # GET /leagues/1/edit
  def edit
    @league = League.find(params[:id])
  end

  # POST /leagues
  # POST /leagues.json
  def create
    # initializing the draft round and team drafting index both to `0`
    @league = League.create(league_params.merge({
      round: 0,
      drafting_index: 0
      }))
    @league.add_teams
    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  def draft
    @league = League.find(params[:id])
    @teams = @league.teams
    @drafted_players = []
    @league.teams.each{ |t|
      t.players.each{ |j|
        @drafted_players << j.id}
      }
    @players = Player.where.not(:id => @drafted_players)
    # read index from @league instead of url param
    @index = @league.drafting_index
    # @round = params[:round].to_i || 1
    @current_team = @teams[@index]
    @positions = ['QB', 'RB', 'WR', 'TE', 'DEF', 'PK']
  end

  def update
    @league = League.find(params[:id])
    @league.update(league_params)
    redirect_to league_path
  end

  def destroy
    @league = League.find(params[:id])
    @league.destroy
    redirect_to leagues_path(@league)
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name)
    end

    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_with(model: league, local: true) do |form| %>
  <% if league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :league_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leagues/draft.html.erb
<h2>Now drafting for: <%= @current_team.name %></h2>
<% # Showing the round number
%><h2>Round: <%= @league.round + 1 %></h2>

<div class="draft_board">
  <div class="teams">
      <% @league.teams.each do |t|%>
        <p><%= t.name %></p>
        <% t.players.each do |p| %>
            <li class="picked_players"><%= p.position %>  <%=  p.name %></li>
        <% end %>
      <% end %>
  </div>

  <div class="all_players">
    <div>
      <h3>All Available Players</h3>
        <% @players.each do |player| %>
          <li>
            <%= player.rank %> <%= player.name %> <%= player.position %> <%= player.nfl_team %>
            <%= link_to "Draft", league_team_player_draft_path(@league, @current_team, player, index: (@index)), method: :post %>
          </li>
        <% end %>
    </div>
  </div>

  <div class="players_by_pos">
    <% for pos in @positions do %>
      <div>
        <h3>All Available <%= pos %>s</h3>
        <% @players.where(:position => pos).each do |player| %>
        <li>
          <%= player.rank %> <%= player.name %> <%= player.nfl_team %>
          <%= link_to "Draft", league_team_player_draft_path(@league, @current_team, player, index: (@index)), method: :post %>
        </li>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<p id="notice"><%= notice %></p>


<div class="hero">
  <div class="new_draft">
    <div><%= link_to 'Draft Now', new_league_path %></div>
  </div>
</div>
<div class="index_copy">
  <div class="view_players">
    <h2>Find the Best Players</h2>
      <div class="button1">
        <div><%= link_to 'Research Players', players_path %></div>
      </div>
    <ul>
      <li>Research your favorite players.</li>
      <li>Plan your draft strategy.</li>
      <li>Get an edge on your competition</li>
    </ul>
  </div>
  <div class="draft_now">
    <h2>Draft the Perfect Team</h2>
    <div class="button1">
      <div><%= link_to 'Draft Now', new_league_path %></div>
    </div>
    <ul>
      <li>Complete mock drafts in minutes with no waiting between picks.</li>
      <li>Mock with custom settings including keepers, scoring rules & roster positions.</li>
      <li>Quickly test different draft strategies to see what works best.</li>
    </ul>
  </div>
</div>

app/views/leagues/index_original.html.erb
<p id="notice"><%= notice %></p>

<h1>Leagues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @league.name %>
</p>

<ul>
<%
  # We need to use the singular league_team_path helper here to build a
  # path for the one team /leagues/:league_id/teams/:id

  # the plural league_teams_path helper would build
  # a path for the teams index /leagues/:league_id/teams
%>
  <% for team in @league.teams %>
    <li><%= link_to team.name, league_teams_path(@league, team) %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %> |
<%= link_to 'Delete', league_path(@league), method: :delete %> |
<%= link_to 'Start Draft', draft_league_path(@league) %>