config/routes.rb
Rails.application.routes.draw do

  root to: 'leagues#index'

  resources :leagues do
    resources :teams do
      resources :players do
        post 'draft'
      end
    end
    resources :plays_on
    member do
      get 'draft'
    end
  end

  resources :players 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plays_on.rb
class PlaysOn < ApplicationRecord
  belongs_to :team
  belongs_to :player
end

app/controllers/plays_on_controller.rb
class PlaysOnController < ApplicationController

  def new
    @players = Player.all

  end

  def create
    @player = Player.find(params[:post_id])
    @team = Team.find_or_create_by(name: params[:name])
    @player.plays_on.create(team: @team)
    redirect_to player_path(@player)
  end

end

app/views/plays_on/new.html.erb
<h1>Working</h1>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Position</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.rank %></td>
        <td><%= link_to player.name, player %></td>
        <td><%= player.position %></td>
        <td><%= player.nfl_team %></td>
        <td><%= link_to 'Draft', new_player_plays_on_path(player) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<ul>
  <% @artist.songs.each do |song| %>
    <li>
      <%= link_to "#{song.title} (#{song.album})", song_path(song) %>

      # If this song has already been favorited, set the link to remove favorite.
      <% if song.users.include? current_user %>
        <%= link_to "&hearts;".html_safe, remove_favorite_song_path(song), method: :delete, class: "fav" %>
      # If the song has not been favorited, set the link to add favorite.
      <% else %>
        <%= link_to "&hearts;".html_safe, add_favorite_song_path(song), method: :post, class: "no-fav" %>
      <% end %>

    </li>
  <% end %>
</ul>